#makes IO single cell simulation for subthreshold oscillation parameters exploration

NAME = IOSim

CC = icl

DEFINES = 

CFLAGS = $(DEFINES) -nologo -fast -O2 -Oa -Qvec-guard-write -Qipo -Qopenmp -arch:SSE4.1 -MD

RM = rm

INCLUDEPATH = ./includes
SRCPATH = ./src
OUTPUTPATH = ./output

COMMONINCS = $(INCLUDEPATH)/common.h
